theme: jekyll-theme-minimal
title: Hello!
description: Feel free to stalk my research with the info available in this website :)
logo: assets/fellipe.jpg
email: erica@cvlab.cs.tsukuba.ac.jp
linkedin: erica-shimomoto
researchgate: Erica-Kido-Shimomoto-2
