theme: jekyll-theme-minimal
title: .
description: Here you cand find all my academic information, if you have any doubt, feel free to contact me!
logo: assets/fellipesimas.jpg
email: simas.fellipe@gmail.com
linkedin: fellipe-dias-tavares-de-simas-839baa215/
researchgate: Fellipe-Dias-Tavares-De-Simas
