theme: jekyll-theme-minimal
title: .
description: Here you cand find all my academic information, if you have any doubt, feel free to contact me!
logo: assets/fellipe.jpg
email: simas.fellipe@gmail.com
linkedin: erica-shimomoto
researchgate: Erica-Kido-Shimomoto-2
